name: Workflow 1

on:
  workflow_dispatch:

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow 2
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger-workflow-2"}'
